Public Class frmRegister

    Private Sub btnClose_Click(sender As Object, e As EventArgs) Handles btnClose.Click
        Me.Close()

    End Sub

    Private Sub btnPreviewData_Click(sender As Object, e As EventArgs) Handles btnPreviewData.Click

        txtRegistrationPreview.Text = ""
        txtRegistrationPreview.AppendText("=============================================" + vbNewLine)
        txtRegistrationPreview.AppendText("=========THE KENYA COMMERCIAL BANK========" + vbNewLine)
        txtRegistrationPreview.AppendText("=============================================" + vbNewLine)
        txtRegistrationPreview.AppendText("NAME: " + vbTab & txtFirstName.Text + vbTab & txtMiddleName.Text + vbTab & txtLastName.Text + vbNewLine)
        txtRegistrationPreview.AppendText("Sex: " + vbTab & cboSex.Text + vbNewLine)
        txtRegistrationPreview.AppendText("ID Card: " + vbTab & txtIdCard.Text + vbNewLine)
        txtRegistrationPreview.AppendText("Date: " + vbTab & DateTimePicker1.Value + vbNewLine)

        txtRegistrationPreview.AppendText(vbNewLine)
        txtRegistrationPreview.AppendText("=============================================" + vbNewLine)
        txtRegistrationPreview.AppendText("Personal contacts" + vbNewLine)
        txtRegistrationPreview.AppendText("=============================================" + vbNewLine)
        txtRegistrationPreview.AppendText("Postal address: " + vbTab & txtPostalAddress.Text + vbNewLine)
        txtRegistrationPreview.AppendText("Postal code: " + vbTab & txtPostalCode.Text + vbNewLine)
        txtRegistrationPreview.AppendText("Town: " + vbTab & txtTown.Text + vbNewLine)
        txtRegistrationPreview.AppendText("Country: " + vbTab & txtCountry.Text + vbNewLine)
        txtRegistrationPreview.AppendText("E-mail: " + vbTab & txtEmail.Text + vbNewLine)
        txtRegistrationPreview.AppendText("Phone number: " + vbTab & txtPhoneNumber.Text + vbNewLine)

        txtRegistrationPreview.AppendText(vbNewLine)
        txtRegistrationPreview.AppendText("=============================================" + vbNewLine)
        txtRegistrationPreview.AppendText("Bank details" + vbNewLine)
        txtRegistrationPreview.AppendText("=============================================" + vbNewLine)
        txtRegistrationPreview.AppendText("Brach name: " + vbTab & txtBranchName.Text + vbNewLine)

        txtRegistrationPreview.AppendText(vbNewLine)
        txtRegistrationPreview.AppendText("=============================================" + vbNewLine)
        txtRegistrationPreview.AppendText("Employment details" + vbNewLine)
        txtRegistrationPreview.AppendText("=============================================" + vbNewLine)
        txtRegistrationPreview.AppendText("Employment: " + vbTab & cboEmployment.Text + vbNewLine)
        txtRegistrationPreview.AppendText("Company of work: " + vbTab & txtCompanyOfWork.Text + vbNewLine)
        txtRegistrationPreview.AppendText("Account type: " + vbTab & cboAccountType.Text + vbNewLine)
        txtRegistrationPreview.AppendText("=============================================" + vbNewLine)

        txtRegistrationPreview.AppendText(vbNewLine)
        txtRegistrationPreview.AppendText("Generated by the Kenya Commercial Bank system" + vbNewLine)
        
    End Sub

    Private Sub btnSaveData_Click(sender As Object, e As EventArgs) Handles btnRegister.Click
        

        Dim firstName As String
        Dim lastName As String
        Dim middleName As String
        Dim idCard As Long
        Dim sex As String
        Dim postalAddress As Integer
        Dim postalCode As Integer
        Dim town As String
        Dim country As String
        Dim email As String
        Dim phoneNumber As String
        Dim branchName As String
        Dim employment As String
        Dim companyOfWork As String
        Dim accountType As String
        Dim password As String
        Dim generatedAccountNumber As String
        Dim kraPin As String


        firstName = (txtFirstName.Text)
        lastName = (txtLastName.Text)
        middleName = (txtMiddleName.Text)
        sex = (cboSex.Text)
        idCard = (txtIdCard.Text)
        postalAddress = (txtPostalAddress.Text)
        postalCode = (txtPostalCode.Text)
        town = (txtTown.Text)
        country = (txtCountry.Text)
        email = (txtEmail.Text)
        phoneNumber = (txtPhoneNumber.Text)
        branchName = (txtBranchName.Text)
        employment = (cboEmployment.Text)
        companyOfWork = (txtCompanyOfWork.Text)
        accountType = (cboAccountType.Text)
        password = (txtPassword.Text)
        generatedAccountNumber = (txtGeneratedAccountNumber.Text)
        kraPin = (txtKraPin.Text)


        If cboSex.SelectedItem = "Male" Then cboSex.Text = "Male" Else If cboSex.SelectedItem = "Female" Then cboSex.Text = "Female"

        If cboAccountType.SelectedItem = "Fixed account" Then cboAccountType.Text = "Fixed account" Else If cboAccountType.SelectedItem = "Savings account" Then cboAccountType.Text = "Savings account"

        If cboEmployment.Text = "Employed" Then cboEmployment.Text = "Employed" Else If cboEmployment.Text = "Self employed" Then cboEmployment.Text = "Self employed"


        

        If txtFirstName.Text = "" Or
            txtLastName.Text = "" Or
            txtMiddleName.Text = "" Or
            cboSex.Text = "" Or
            txtIdCard.Text = "" Or
            txtPostalCode.Text = "" Or
            txtTown.Text = "" Or
            txtCountry.Text = "" Or
            txtEmail.Text = "" Or
            txtPhoneNumber.Text = "" Or
            txtBranchName.Text = "" Or
            cboEmployment.Text = "" Or
            cboAccountType.Text = "" Or
            txtPassword.Text = "" Or
            txtGeneratedAccountNumber.Text = "" Or
            txtKraPin.Text = "" Or
            txtPostalAddress.Text = "" Then
            MsgBox("provide all details", MsgBoxStyle.Information)
        Else
            My.Settings.firstName = txtFirstName.Text
            My.Settings.lastName = txtLastName.Text
            My.Settings.middleName = txtMiddleName.Text
            My.Settings.sex = cboSex.Text
            My.Settings.idCard = txtIdCard.Text
            My.Settings.postalAddress = txtPostalAddress.Text
            My.Settings.postalCode = txtPostalCode.Text
            My.Settings.town = txtTown.Text
            My.Settings.country = txtCountry.Text
            My.Settings.kraPin = txtKraPin.Text
            My.Settings.email = txtEmail.Text
            My.Settings.phoneNumber = txtPhoneNumber.Text
            My.Settings.branchName = txtBranchName.Text
            My.Settings.employment = cboEmployment.Text
            My.Settings.generatedAccountNumber = txtGeneratedAccountNumber.Text
            My.Settings.accountType = cboAccountType.Text
            My.Settings.password = txtPassword.Text
            My.Settings.Save()

            MsgBox("Registration Succesful", MsgBoxStyle.Information)
        End If

    End Sub

 
    Private Sub cboEmployment_SelectedIndexChanged(sender As Object, e As EventArgs) Handles cboEmployment.SelectedIndexChanged

        If cboEmployment.SelectedItem = "Self employed" Then txtCompanyOfWork.Enabled = False Else If cboEmployment.SelectedItem = "Employed" Then txtCompanyOfWork.Enabled = True
    End Sub


    Private Sub btnAutoGenerate_Click(sender As Object, e As EventArgs) Handles btnAutoGenerate.Click
        Dim rn As New Random
        txtGeneratedAccountNumber.Text = (rn.Next(100000000, 999999999))
    End Sub

  
    Private Sub btnTermsOfService_Click(sender As Object, e As EventArgs) Handles btnTermsOfService.Click
        frmTermsAndConditions.show()
    End Sub
End Class